name = "SymDiff"
uuid = "d0f7bc7f-cd2f-4cc8-8336-d901b45b4b8e"
authors = ["Jukka Aho <ahojukka5@gmail.com>"]
version = "0.1.0"

[compat]
julia = "â‰¥ 1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
